version: '3.9'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_TEST_ADMIN_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_TEST_ADMIN_PASS}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    entrypoint: ['/usr/bin/mongod', '--replSet', 'rsmongo', '--bind_ip_all']

  mongo_db2:
    container_name: mongo_db2
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_TEST_ADMIN_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_TEST_ADMIN_PASS}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    entrypoint: ['/usr/bin/mongod', '--replSet', 'rsmongo', '--bind_ip_all']
