export enum StatusCode {
	UNAUTHORIZED = 'UNAUTHORIZED',
	BAD_REQUEST = 'BAD_REQUEST',
	INTERNAL_SERVER = 'INTERNAL_SERVER',
	NOT_FOUND = 'NOT_FOUND',
	CONFLICT = 'CONFLICT',
	CONTINUE = 'CONTINUE',
}
